  name: Test Schedule

  on:
    schedule:
      - cron: '*/15 * * * *'  # Runs every 15 minutes

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - name: Echo Time
          run: echo "The time is $(date)"
